language: "en-US"
enable_free_tier: true

reviews:
  profile: "chill"
  request_changes_workflow: false
  high_level_summary: true
  review_status: true
  commit_status: true
  fail_commit_status: false
  changed_files_summary: true
  suggested_reviewers: true

  path_filters:
    - "!*.md"
    - "!*.json"
    - "!node_modules/**"
    - "!dist/**"
    - "!coverage/**"
    - "!.angular/**"
    - "!.git/**"
    - "src/**/*.ts"
    - "src/**/*.html"
    - "src/**/*.css"

  auto_review:
    enabled: true
    base_branches:
      - "main"
      - "master"
      - "dev"
    drafts: false

  finishing_touches:
    docstrings:
      enabled: true
    unit_tests:
      enabled: true

chat:
  auto_reply: true
